name: device_data_plugin
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/king-kloy/device_data_plugin.git
repository: https://github.com/king-kloy/device_data_plugin.git

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^8.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1


flutter:

  